class TestFixtures(unittest.TestCase):
  def test(self):
    self.assertNotEqual(mi_nombre, None)
  def test(self):
    self.assertEqual(type(mi_nombre), str)
  def test(self):
    self.assertNotEqual(mi_edad, None)
  def test(self):
    self.assertEqual(type(mi_edad), int)